#!/usr/bin/python3

mapping = {
  'American Restaurant': 'Food',
  'Antique Shop': 'Art',
  'Argentinian Restaurant': 'Food',
  'Art Gallery': 'Art',
  'Art Museum': 'Art',
  'Asian Restaurant': 'Food',
  'Auditorium': 'Entertainment',
  'BBQ Joint': 'Food',
  'Bakery': 'Food',
  'Bar': 'Bar',
  'Basketball Stadium': 'Sport',
  'Beach Bar': 'Bar',
  'Beach': 'Entertainment',
  'Bed & Breakfast': 'Food',
  'Beer Garden': 'Bar',
  'Boat or Ferry': 'Entertainment',
  'Bookstore': 'Entertainment',
  'Boutique': 'Shopping',
  'Breakfast Spot': 'Food',
  'Brewery': 'Food',
  'Burger Joint': 'Food',
  'Caf\u00e9': 'Food',
  'Chinese Restaurant': 'Food',
  'Cocktail Bar': 'Bar',
  'Coffee Shop': 'Food',
  'College Stadium': 'Sport',
  'Concert Hall': 'Entertainment',
  'Cosmetics Shop': 'Beauty',
  'Cuban Restaurant': 'Food',
  'Cultural Center': 'Art',
  'Department Store': 'Shopping',
  'Dessert Shop': 'Food',
  'Diner': 'Food',
  'Distillery': 'Food',
  'Dog Run': 'Park',
  'Event Space': 'Entertainment',
  'Farmers Market': 'Shopping',
  'Festival': 'Entertainment',
  'Food Truck': 'Food',
  'French Restaurant': 'Food',
  'Furniture / Home Store': 'Shopping',
  'Gastropub': 'Bar',
  'General Entertainment': 'Entertainment',
  'Gourmet Shop': 'Food',
  'Grocery Store': 'Shopping',
  'Gym / Fitness Center': 'Sport',
  'Harbor / Marina': 'Entertainment',
  'Hardware Store': 'Shopping',
  'Historic Site': 'Entertainment',
  'Hotel Bar': 'Bar',
  'Indie Movie Theater': 'Theater',
  'Internet Cafe': 'Food',
  'Italian Restaurant': 'Food',
  'Japanese Restaurant': 'Food',
  'Jazz Club': 'Entertainment',
  'Karaoke Bar': 'Bar',
  'Latin American Restaurant': 'Food',
  'Lighthouse': 'Entertainment',
  'Lounge': 'Bar',
  'Mediterranean Restaurant': 'Food',
  'Metro Station': 'Transportation',
  'Mexican Restaurant': 'Food',
  'Middle Eastern Restaurant': 'Food',
  'Miscellaneous Shop': 'Shop',
  'Molecular Gastronomy Restaurant': 'Food',
  'Movie Theater': 'Theater',
  'Multiplex': 'Shopping',
  'Music Venue': 'Entertainment',
  'Nail Salon': 'Beauty',
  'New American Restaurant': 'Food',
  'Nightclub': 'Bar',
  'Other Great Outdoors': 'Entertainment',
  'Park': 'Entertainment',
  'Performing Arts Venue': 'Art',
  'Piano Bar': 'Bar',
  'Pizza Place': 'Food',
  'Pub': 'Bar',
  'Record Shop': 'Shopping',
  'Resort': 'Hotel',
  'Restaurant': 'Food',
  'Rock Club': 'Club',
  'Roof Deck': 'Entertainment',
  'Salad Place': 'Food',
  'Salon / Barbershop': 'Beauty',
  'Sandwich Place': 'Food',
  'Scandinavian Restaurant': 'Food',
  'Seafood Restaurant': 'Food',
  'Ski Area': 'Entertainment',
  'Ski Chairlift': 'Entertainment',
  'Ski Lodge': 'Entertainment',
  'Smoke Shop': 'Shopping',
  'Social Club': 'Entertainment',
  'Southern / Soul Food Restaurant': 'Food',
  'Spa': 'Beauty',
  'Spanish Restaurant': 'Food',
  'Sporting Goods Shop': 'Shopping',
  'Sports Bar': 'Bar',
  'Street Food Gathering': 'Food',
  'Supermarket': 'Shopping',
  'Sushi Restaurant': 'Food',
  'Tapas Restaurant': 'Food',
  'Thai Restaurant': 'Food',
  'Thrift / Vintage Store': 'Shopping',
  'Train Station': 'Transportation',
  'Transportation Service': 'Transportation',
  'Whisky Bar': 'Bar',
  'Wine Bar': 'Bar',
  'Wine Shop': 'Food',
  'Winery': 'Food'
}

import json
with open('/vagrant/tmp/osn-data/venue_categories.json', 'r') as file:
  venue_categories = json.load(file)

for venue, categories in venue_categories.items():
  for i in range(len(categories)):
    if categories[i] in mapping:
      categories[i] = mapping[categories[i]]

with open('/vagrant/tmp/osn-data/venue_categories2.json', 'w') as file:
  json.dump(venue_categories, file, sort_keys=True)
